### ISSUE TITLE
Ripanga Overflow

### ISSUE THREAD

**Issue by brock-noah** [procore/particles#106]
When the dropdown is longer than the table, part of the dropdown is hidden.

<img width="574" alt="screen shot 2017-05-31 at 11 50 31 am" src="https://cloud.githubusercontent.com/assets/5582147/26648477/745af9fc-45f7-11e7-873d-6436180fc3a9.png">

This is caused by a parent setting overflow and an absolute positioned child respecting that overflow.
https://github.com/chrisarevir/component-library/blob/master/tables/ripanga/src/Ripanga.scss#L9

**Comment by nickwmurphy** [comment]
Issue fixed in #129.
