### ISSUE TITLE
Bulk Editor imports dependency that's not within the scope of the repository

### ISSUE THREAD

**Issue by mboperator** [procore/particles#291]
<img width="948" alt="screen shot 2017-08-24 at 2 08 39 pm" src="https://user-images.githubusercontent.com/1007233/29688798-c29ae4bc-88d5-11e7-82da-443c72a73d6c.png">

Where does stylesheet compose come from?

**Comment by ben-burlingham** [comment]
The stylesheet composer is in the `shared` directory.  

I'm not getting this error when running `prod`, `dev` or `sandbox` mode.  Perhaps it was fixed already, are you still having this issue?

**Comment by mboperator** [comment]
No longer an issue in development
