### ISSUE TITLE
yarn sandbox fails for date select after a clean install

### ISSUE THREAD

**Issue by mboperator** [procore/particles#293]
<img width="954" alt="screen shot 2017-08-24 at 2 14 49 pm" src="https://user-images.githubusercontent.com/1007233/29689042-9f823dbc-88d6-11e7-929e-818fbe9d43bf.png">

Removing `disableHostCheck: true` from `webpack.dev.config.js` fixes it. Is this line required?
Updating `webpack-dev-server` to `^2.7.1` in the failing component also fixes the issue.

**Comment by mcclayton** [comment]
@mboperator Is this fixed? Can this be closed now?

**Comment by ben-burlingham** [comment]
This has been fixed.
