### ISSUE TITLE
Unit Testing Framework

### ISSUE THREAD

**Issue by mcclayton** [procore/particles#296]
Since the goal of these are to be heavily shared/reusable components, test coverage will be vital.
I'd absolutely love to help get tests in this repo and more than happy to take the lead on that.
Do we envision having a `yarn test` from within each particle component and co-located tests? Or a root level `yarn test` that runs tests for all components with tests in a root level folder?
Or some other option?

**Comment by ben-burlingham** [comment]
Wonderful! Thank you.

There's no vision as of yet.  The test per particle sounds more in line with the architectural goals of this initiative, but both ideas are great.  We have three main concerns:

- Simplicity
- Speed
- Patterns that remain agnostic and support multiple frameworks

The `yarn test` plan is right on with all three of these - the implementing team can use whatever framework they wish, and just hook the tests to `yarn test`. Love it.  

I'd also like to make the test suite non-optional, but it doesn't need to be run on every `yarn dev`.  Perhaps we can work it into a `yarn publish` command, which prompts for a couple of things, runs the test suite, and preps a published stack on success.  I think @RyanFuentes  is working on a tiny solution for the publish command; we can chat in person if you like.

Thanks again! Really looking forward to this.  Also, would love to get some headless rendering benchmark solutions in place 🤔  but this is a stretch goal.
