### ISSUE TITLE
Modal 2.0 proposal

### ISSUE THREAD

**Issue by Marswang92** [procore/particles#317]
1. Remove `beforeOpen`, `afterOpen`, `beforeClose`, `afterClose` props.
2. `size` props decide the modal's `max-height` and `width`.
3. Lock body scroll when modal is open.
4. Remove `disableHeader` prop.
5. Introduce `CSSTransition` for animation.

**Comment by ben-burlingham** [comment]
Sounds good just a couple requests:

- `size` is solved with stylesheet
- Let's use the `slot` pattern from other components: `slotHead`, `slotBody`, `slotFooter`

**Comment by ben-burlingham** [comment]
https://github.com/procore/particles/pull/365
