### ISSUE TITLE
Script locations and philosophy

### ISSUE THREAD

**Issue by ben-burlingham** [procore/particles#346]
With simple architectures, adding libs and scripts and hooks and fun things are an easy temptation.

There are things that should be scripted (initial startup, semver/readme/prod flow, etc) but to avoid shared bloat and trash dumps we need a clear path on where to put them and what scripts are needed.

There's currently a `shared` folder which is in danger of being a trash dump - it's got a few shared utils.  A `scripts` folder may have the same fate. How should these be handled?

**Comment by mboperator** [comment]
I think we have to ensure that each script in the `scripts` folder is simple and has a very clear, specific purpose. 

Ideally they correspond 1:1 with an `npm script`, and should deal more with orchestrating and summarizing the result of the activity per directory.

**Comment by ben-burlingham** [comment]
Right with ya.  Potential issues, even just from today's conversation:

- Init script becomes a one-off
- Single-script-single-functionality sounds like we'll have biiiiig scripts :/

A 1:1 sounds like a great pattern though.  I wonder if there's a balance between that strict-ness and smaller slices.

**Comment by ben-burlingham** [comment]
Closing, solution will evolve over time with active POCs.
