### ISSUE TITLE
Breadcrumbs

### ISSUE THREAD

**Issue by brock-noah** [procore/particles#363]
I would like to introduce a breadcrumb component. It should be able to support at least:
 - `a`
 - `div` with `onClick`
 - react router `Link`

I have two propositions:
```
// 1
<Breadcrumbs>
  <Crumb componentClass={Link} to="/x">X</Crumb>
  <Crumb componentClass={Link} to="/x/y">Y</Crumb>
  <ActiveCrumb>Current</ActiveCrumb>
</Breadcrumbs>

// 2
<Breadcrumbs>
  <Crumb><Link to="/x">X</Link></Crumb>
  <Crumb><Link to="/x/y">Y</Link></Crumb>
  <ActiveCrumb>Current</ActiveCrumb>
</Breadcrumbs>
```

I can see 1 being easier to change the style on the `Crumb`s because the element (`a`) can be styled directly (think about hover effect). There might be problems with prop confusion/conflicts, which props are for the breadcrumb and which are for the component being render. Possibly `<Crumb componentClass={Link} componentProps={{to: "/x"}}>` could fix this. Option 2 could allow easier work with children and clarity of props.

Also not sure if `ActiveCrumb` is necessary, it might only be used for styling, and CSS `:last-child` could solve that.

Thoughts, opinions?

**Comment by ben-burlingham** [comment]
Cool! I think what you propose could be achieved with just basic markup:

    ```
    // ...where onClick is a handler with analytics, redirects, 
    const crumbs = data.map(d => 
       // ....not sure how 'active' is determined; it could be passed in with the data or as a prop
        (<div className={cx(styles.breadcrumb, { active: d.active })} onClick={this.onClick}>
            {d.text}
        </div>)
    );

    <div className={styles.breadcrumbContainer}>
       {crumbs}
    </div>```

    ...etc.  At this point, it turns into a pretty simple particle; mostly a style and analytics wrapper that can be used in either a page-reload architecture or a SPA situation.

Props would be something like: `data, onAnalytics, stylesheets`.

**Comment by brock-noah** [comment]
Why would you prefer an array with attributes over an array of children with props? Is it for the self closing tag that can be mounted on a page?

**Comment by ben-burlingham** [comment]
Not sure exactly what you mean?  `{crumbs}` is an array of `<div>` elements.  My point is mostly that declaring a `<Crumb>` element is not very necessary, since it's just a fancy wrapper for a `<div>`.  `<ActiveCrumb>` is the same for a `<div>` with an active class on it.

**Comment by ben-burlingham** [comment]
Also, I'd be wary of a React Router dependency - devs implementing a Breadcrumb may not (will probably not) be using React router.  It may be best to have a rendering function that wraps children in a predefined style.

**Comment by brock-noah** [comment]
The `Breadcrumb` component will not have react router dependency.

```
// A
<Breadcrumbs>
  <Crumb>First</Crumb>
  <Crumb active>Current</Crumb>
</Breadcrumbs>

// B
<Breadcrumbs data={[{
    title: 'First'
  }, {
    title: 'Current',
    active: true
  }]}
/>
```

I think it is more clear to match the API of a component, not the shape of an object.
Option A allows easier default values and is more declarative. Option B could cause additional renders if other data is stored in that array. Someone using an immutable data structure, now needs to call `toJS` to change data types. I think option A separates how the data is stored and how to pass data.

**Comment by ben-burlingham** [comment]
Great point!  

Aren't those two cases exclusive?  The declaration in a client would look like B, the internal implementation would look like A.  `<Crumb>`s would necessarily be generated from the data passed in at declaration.

**Comment by brock-noah** [comment]
I want to give power to components rather than god objects.

Take the [tab example](http://www.material-ui.com/#/components/tabs) from material ui. The children of the container component is a `Tab`, and the children of that is the tab content. It is very expressive and easy to understand.
```
<Tabs>
  <Tab title="List View">
    <Table />
  </Tab>
  <Tab title="Card View">
    <Cards />
  </Tab>
</Tabs>
```

A library shouldn't edged you to name keys something particular (the component prop is already a key) or have a shape contract to match a component. A single import should provide multiple components allowing you to declare what you want.

https://ant.design/components/tree-select
https://react-bootstrap.github.io/components.html#carousels
http://reactdesktop.js.org/docs/windows/nav-pane#examples
https://react.semantic-ui.com/modules/modal#modal-example-basic

**Comment by ben-burlingham** [comment]
@brock-noah Can you just build what you have in mind?  The point of particles is not to block designs or teams from moving forward but rather to allow different designs to co-exist, and we can all implement and discuss. 

Proliferation is a reality, discussions are purely theoretical until implementations can be tested - let's give it a try!

**Comment by brock-noah** [comment]
Implemented a solution like 1 here https://github.com/procore/particles/pull/492
