### ISSUE TITLE
Calendar

### ISSUE THREAD

**Issue by kedarmoghe** [procore/particles#456]
- [ ] Comprehensive component testing.  

- [x] Break down markup into sub components, ie. Calendar.Cell, etc. (makes it easier for testing).  (_reporter: Michael Clayton_)

- [ ] i18n for strings like "Single Day", "Date Range"

- [ ] Error handling.

- [x] Add prop types check.

- [ ] Address accessibility concerns. (_reporter: Michael Clayton_)

- [ ] Handle FontAwesome dependency by pulling in what's required from some shared css directory.  (_reporter: Michael Clayton, Brock Noah_)

- [x] Styling bugs/improvements.

**Comment by kedarmoghe** [comment]
Please let me know if other things also and I will add them.  Thanks

**Comment by ben-burlingham** [comment]
Should these be separate issues? Checklists tend to leave the issue open for a long time waiting for that one stubborn one to get done...
