### ISSUE TITLE
Include example screenshots on readmes

### ISSUE THREAD

**Issue by dannyphillips** [procore/particles#702]
# Problem: 
It's difficult to know what particles look and feel like when browsing github. Because of this, it's hard to know whether I should use an existing particle, update it, or create a new one.

# Solution: 
It would be great to see a brief screenshot of each particles.

# Examples
Here is a list of screenshots for all the particles that I'd like to propose including in the readme's. 

### breadcrumbs
![jvmj8mwy52](https://user-images.githubusercontent.com/8366399/34238653-a5186c0e-e5b7-11e7-9ba4-8ba7016b5a4b.gif)

### bulk editor
![bulk_edit](https://user-images.githubusercontent.com/8366399/34238575-46ac9474-e5b7-11e7-923a-f365c9a6e539.gif)

### checkbox
![checkbox](https://user-images.githubusercontent.com/8366399/34238611-6e211002-e5b7-11e7-8e56-c38fe62e324b.gif)

### calendar
![calendar](https://user-images.githubusercontent.com/8366399/34238485-bb37b20c-e5b6-11e7-909f-c3b1b0842a05.gif)

### coach marks
![coach_marks](https://user-images.githubusercontent.com/8366399/34238716-08fb9d9a-e5b8-11e7-8706-a6c6adf56513.gif)

### crud permission table
![crud_table](https://user-images.githubusercontent.com/8366399/34238802-8c5d4ef4-e5b8-11e7-94a1-8b8096fbfee4.gif)

### date-select
![date_select](https://user-images.githubusercontent.com/8366399/34238874-ec68b9e6-e5b8-11e7-841d-9399d716e41e.gif)

### dialog
![dialog](https://user-images.githubusercontent.com/8366399/34239010-99f0c87e-e5b9-11e7-90db-ff1d517521eb.gif)

### feedback-banner
![beta_feedback](https://user-images.githubusercontent.com/8366399/34239089-fd1432ba-e5b9-11e7-9d97-68625bbe31b0.gif)

### file-explorer
![file-explorer](https://user-images.githubusercontent.com/8366399/34239111-1be4a490-e5ba-11e7-9875-fa4c66d6db34.gif)

### filters
![filters](https://user-images.githubusercontent.com/8366399/34239180-79523ed0-e5ba-11e7-9bac-f184d043eda3.gif)

### info-grid
![info-grid](https://user-images.githubusercontent.com/8366399/34239232-d0cf977a-e5ba-11e7-8e03-4049fc52da42.gif)

### list-partial
![list-partial](https://user-images.githubusercontent.com/8366399/34239320-856f611a-e5bb-11e7-9475-a1e3717173b2.gif)

### modal
![modal](https://user-images.githubusercontent.com/8366399/34238431-670b2402-e5b6-11e7-8dec-0bf3f8a32984.gif)

### navigation-tiers
![navigation-tiers](https://user-images.githubusercontent.com/8366399/34239375-d47c7158-e5bb-11e7-9ced-86337f059beb.gif)

### notification-bar
![notification-bar](https://user-images.githubusercontent.com/8366399/34239425-2b3b4e6a-e5bc-11e7-8bc1-04c4f5c1da79.gif)

### paginator
![paginator](https://user-images.githubusercontent.com/8366399/34239494-8d153ace-e5bc-11e7-9b99-c70671f79670.gif)

### phone-input
![phone-input](https://user-images.githubusercontent.com/8366399/34239527-baf30840-e5bc-11e7-96a8-891ce31a8cb3.gif)

### radio
![radio](https://user-images.githubusercontent.com/8366399/34239548-de469f3c-e5bc-11e7-92af-094b60a140a6.png)

### scoped-scroll
![scoped-scroll](https://user-images.githubusercontent.com/8366399/34239591-38d12f76-e5bd-11e7-8d9e-c3573637f793.gif)

### search-bar
![search-bar](https://user-images.githubusercontent.com/8366399/34239625-782b0d0e-e5bd-11e7-9c20-f28a0a92be00.gif)

### select
![select](https://user-images.githubusercontent.com/8366399/34239679-c64437c2-e5bd-11e7-873f-ba2d9e01bdca.gif)

### spinner
![spinner](https://user-images.githubusercontent.com/8366399/34239692-e1d1c1f8-e5bd-11e7-9940-dc2fb3dd41b0.gif)

### sticky-footer
![sticky-footer](https://user-images.githubusercontent.com/8366399/34239824-e908bf5c-e5be-11e7-83eb-7106140d78bd.gif)

### table
![table](https://user-images.githubusercontent.com/8366399/34239862-2189eda6-e5bf-11e7-8254-b4e2d94ccdf4.gif)

### table-view-control
![table-view-toggle](https://user-images.githubusercontent.com/8366399/34239893-5e0d0916-e5bf-11e7-821d-8d408a3f65c2.gif)

### tabs
![tabs](https://user-images.githubusercontent.com/8366399/34239933-a27d2c3e-e5bf-11e7-86ea-2b198436edf5.gif)

### text-input
![text-input](https://user-images.githubusercontent.com/8366399/34239950-bf145a3e-e5bf-11e7-9189-59640e57644a.gif)

### tiered-select
![tiered-select](https://user-images.githubusercontent.com/8366399/34240012-2543b2f0-e5c0-11e7-92e7-c63c64e0efa7.gif)

### token
![token](https://user-images.githubusercontent.com/8366399/34240035-42c16b6a-e5c0-11e7-919c-977fc9576c9f.gif)

### tooltip
![tooltip](https://user-images.githubusercontent.com/8366399/34240057-6809cc78-e5c0-11e7-87f3-a87ef57aa21c.gif)

### uploader
![uploader](https://user-images.githubusercontent.com/8366399/34240121-b8f9d484-e5c0-11e7-906c-bd2d0505410a.gif)

**Comment by ben-burlingham** [comment]
This is great @dannyphillips - we're super close to a documentation solution and this would fit right in.  

What do you think about just including the `gif` in the particle directory, something like `uploader/screenshot.gif`?

**Comment by ben-burlingham** [comment]
Also noticing that a few of these are out of date (tabs, spinner, filters) so we'll get them up to speed once the pattern is defined.
